kind: Deployment
apiVersion: apps/v1
metadata:
  name: quality-backend-dashboard
  namespace: appstudio-qe
  labels:
    app: quality-dashboard
    app.kubernetes.io/component: quality-backend
    app.kubernetes.io/instance: quality-dashboard
    app.kubernetes.io/name: quality-dashboard
    component: quality-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quality-dashboard
      component: quality-backend
  template:
    metadata:
      labels:
        app: quality-dashboard
        app.kubernetes.io/component: quality-backend
        app.kubernetes.io/instance: quality-dashboard
        app.kubernetes.io/name: quality-dashboard
        component: quality-backend
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 512Mi
          name: quality-backend-dashboard
          command: ["/root/server-runtime"]
          env:
            - name: POSTGRES_ENT_HOST
              value: "postgres-service"
            - name: POSTGRES_ENT_DATABASE
              valueFrom:
                secretKeyRef:
                  name: quality-dashboard-secrets
                  key: storage-database
            - name: POSTGRES_ENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quality-dashboard-secrets
                  key: storage-password
            - name: POSTGRES_ENT_USER
              valueFrom:
                secretKeyRef:
                  name: quality-dashboard-secrets
                  key: storage-user
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: quality-dashboard-secrets
                  key: github-token
          args:
            - "--port=8080"
          securityContext:
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          image: >-
            quay.io/redhat-appstudio/quality-dashboard-backend:latest